### ISSUE TITLE
Support for ZoneId type

### ISSUE THREAD

**Issue by stonio** [vladmihalcea/hibernate-types#102]
Can you add support for `java.time.ZoneId` similar to `org.hibernate.type.descriptor.java.TimeZoneTypeDescriptor`?

**Comment by vladmihalcea** [comment]
I don't know what you are talking about. If you have some improvement idea, you need to send a Pull Request with the fix. I'll review it afterward.

**Comment by izogfif** [comment]
What about hibernate-types-5? I can't find this class in there.

**Comment by vladmihalcea** [comment]
Hibernate supports Java 8 since version 5.2, so the Hibernate Types project follows it.

If you are using Java 8, you should migrate to Hibernate 5.2, 5,3, or 5.4 and use the Hibernate Types 5.2 dependency.

**Comment by izogfif** [comment]
Migration from 5.1.0.Final to 5.2.18.Final leads to infinite number of warnings in run time (because of usage of lots of methods which became deprecated in 5.2) and requires full retest (e.g. in case of default settings being changed). Pretty huge investment to be able to use ZoneId as entity property type.
What's the Java compatibility for hibernate-types-5? If it's Java 6 then yes, I suppose there is no way to back-port the class there.

**Comment by vladmihalcea** [comment]
> What's the Java compatibility for hibernate-types-5? If it's Java 6 then yes, I suppose there is no way to back-port the class there.

That's correct. The `hibernate-types-5`, `hibernate-types-43`, and `hibernate-types-4` are built using JDK 1.6 since there are many legacy projects still running on 1.6. Migrating to Java 8 would break all those projects, hence it cannot happen.

However, you can simply fork the project and backport the `ZoneIdType` to the `hibernate-types-5` module. That's the beauty of open-source. You are free to modify the source code any way you want.
