### ISSUE TITLE
Unexpected dirty checking behavior on collections of POJOs mapped with JsonBinaryType

### ISSUE THREAD

**Issue by mojgh** [vladmihalcea/hibernate-types#138]
# Description

When *reading* entities with collections of POJOs such as TestEntity (see Example 1), updates are performed on the database without the objects being changed.

## Example 1

```java
@TypeDefs({
        @TypeDef(name = "jsonb", typeClass = JsonBinaryType.class)
})
@Entity
public class TestEntity {

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Id
    public int id;

    @Type(type = "jsonb")
    public Collection<TestElement> testElements;


    public static class TestElement implements Serializable {

        static final long serialVersionUID = -8485895696327472738L;

        public String testProperty;

    }

}
```

# Analysis

It appears as if the dirty check on JsonBinaryType properties for collections of POJOs does no longer work as expected.
The problem occurs since [commit-1]. This commit introduces a new dirty checking behavior for JsonBinaryType, when used with collections:

```java
public boolean areEqual(Object one, Object another) {
// ...
	if (one instanceof Collection && another instanceof Collection) {
		return Objects.equals(one, another);
	}
```
[JsonTypeDescriptor](https://github.com/vladmihalcea/hibernate-types/blame/hibernate-types-parent-2.7.0/hibernate-types-5/src/main/java/com/vladmihalcea/hibernate/type/json/internal/JsonTypeDescriptor.java#L89)

I would not expect the usage of java.lang.Object#equals at this point. In my understanding it creates an inconsistency compared to the dirty checking behavior used for non-collection types.
The recursive field by field comparison before [commit-1] is appropriate in my opinion.

# Workaround

Downgrade to the version before [commit-1]: version 2.4.2.

# Links

[commit-1](https://github.com/vladmihalcea/hibernate-types/commit/3147d6d1264712edad334a9b2d71d0ee37aca5db)

**Comment by vladmihalcea** [comment]
Thanks for the analysis. It would be great if you proposed a Pull Request as well. I'll review it once it's ready.

**Comment by mojgh** [comment]
A small project to prove the problem: [hibernate_types_138.zip](https://github.com/vladmihalcea/hibernate-types/files/3701532/hibernate_types_138.zip)

**Comment by vladmihalcea** [comment]
I think it's better to fork the project and create a replicating test case from an existing test case. This way, the test can prevent the issue from occurring in future as well.

**Comment by vladmihalcea** [comment]
[This commit](https://github.com/vladmihalcea/hibernate-types/commit/527c5ae0f9397752cafbb6a7e8027f849b9063cc) proves that everything works as expected. The only case where I found the issue that you are describing is if you are using a Collection of Objects that don't implement equals or hashCode based on the inner properties, so the default `java.lang.Object` implementations are used.

**Comment by cosminseceleanu** [comment]
@vladmihalcea after 4 days of debugging and a lot of logs(including a hot fix) I found that my issue was caused by a similar case. 

> The only case where I found the issue that you are describing is if you are using a Collection of Objects that don't implement equals or hashCode

Is this documented somewhere? Thanks in advance

**Comment by vladmihalcea** [comment]
@cosminseceleanu I think it's useful to add it to the README.md doc. Send me a Pull Request with the change. Thanks.

**Comment by cosminseceleanu** [comment]
@vladmihalcea I updated the docs. Please review.

Off topic: I think this project is missing a contribution guide 😃

**Comment by vladmihalcea** [comment]
Thanks. I'll review it when I have some time. It would be great if there were a Contribution Guide too. You can supply one if you like.

**Comment by 62mkv** [comment]
another half a day spent on hair-pulling due to this issue.. :) 

I decided to bump many things at once - my bad. eventually settled down on this problem. Works fine with `com.vladmihalcea:hibernate-types-52:2.9.0`, dirty UPDATES manifest themselves with `2.10.0`. 

However, I still can't understand what is the root cause, will have to check further. Right now it seems that all of the following:
* entity itself
* POJO that is wrapped in JSON
* and types used in collections of this POJO,
all of it has `equals` and `hashCode` implementation (entity - the one suggested by JPABuddy IntelliJ plugin, the other two - implemented with Lombok)

And no warnings are given in 2.10.1 version either, I guess because `validatePropertyType` only checks if the annotated field type is a `Collection` (which it isn't, in my case) .

I'll see if I can submit a reproducible test project soon.

**Comment by vladmihalcea** [comment]
Usually, this is caused by bad `equals` and `hashCode` implementation in the POJO object that maps the JSON column. 

Most likely you added `equals` and `hashCode` at the entity level only, not for the POJO attributes. This is a standard requirement by the JPA spec too.

**Comment by 62mkv** [comment]
to clarify - by "entity" we mean JPA Entity, by POJO - the type, that is persisted as JSON column, right ? 

So, in this case: 

```java
@Entity
@Table(name = "RA_OUTBOX_RECORDS")
@Getter @Setter @ToString
@TypeDef(
        name = "jsonb",
        typeClass = JsonBlobType.class
)
public class DocumentOutboxRecord {
///
    @Column(name = "PAYLOAD")
    @Type(type = "jsonb")
    DocumentPayloadV10 payload;
///
```

`DocumentOutboxRecord` would be an "entity" and `DocumentPayloadV10` - a POJO? 

and by "implementing equals/hashCode for POJO attributes" we mean that all custom (non-JDK) types, used _inside_ the POJO type, and their attributes in turn, all should have `equals`/`hashCode` implemented (i.e. not inherited from `Object`) ? 

well, if that is correct, then "POJO" and the only custom type used in the POJO definition, they both have `equals` and `hashCode` implementations, generated with Lombok. 

And by the way, I have narrowed down the problem starting point: it was in 2.9.3 version of "hibernate-types-52" artifact. So, with 2.9.0/2.9.1/2.9.2 all is fine (just as with 2.5.2, for example), and with 2.9.3. and all subsequent versions - all goes bust.. Version number being the only difference

**Comment by vladmihalcea** [comment]
> to clarify - by "entity" we mean JPA Entity, by POJO - the type, that is persisted as JSON column, right ?

yes

> DocumentOutboxRecord would be an "entity" and DocumentPayloadV10 - a POJO?

yes

> and by "implementing equals/hashCode for POJO attributes" we mean that all custom (non-JDK) types, used inside the POJO type, and their attributes in turn, all should have equals/hashCode implemented (i.e. not inherited from Object) ?

It depends on the structure of the `DocumentPayloadV10` object. The equals and hashCode should determine whether that object state has changed or not.

> And by the way, I have narrowed down the problem starting point: it was in 2.9.3 version of "hibernate-types-52" artifact. So, with 2.9.0/2.9.1/2.9.2 all is fine (just as with 2.5.2, for example), and with 2.9.3. and all subsequent versions - all goes bust.. Version number being the only difference

You can track the change log to see what caused the issue. At the moment, I'm very busy with other project and won't have the time to investigate issues or do any development for this framework. But, as soon as I have more time (Jan-March 2022) I'll take a look at your fndings.

**Comment by 62mkv** [comment]
Sure, Vlad, this is not to somehow grab your attention or whatever, just for some other future poor soul who might end up in this issue (and most likely myself!) 

I'll check the diff, thanks!

**Comment by vladmihalcea** [comment]
There's this [section](https://github.com/vladmihalcea/hibernate-types#best-practices) in the README file that should prevent people from bumping into this issue. 

Looking forward to checking your analysis.

**Comment by 62mkv** [comment]
Ok, I have a reproduction case but it actually is now even more confusing to me than it was.. the link to reproduction project is: https://github.com/62mkv/hibernate-types-dirty-updates-repro-case

So, the problem is, that when `autoFlush` (after a call to `persist` and before a call to `list`) happens, there's an `FlushEvent#entityEntry` with `loadedState` containing my POJO with both fields equal to `null`. I have _no idea_ where this specific value could be coming from. And the `currentState` is, of course, a proper POJO.  

So, the difference between 2.9.2 and 2.9.3 is that there's no this code in 2.9.2: 

```
        if (one.getClass().equals(another.getClass())) {
            return one.equals(another);
        }
```

which was added as a commit "Unexpected Hibernate dirty checking when using Sets #175".

So in 2.9.3 and later, this code _is present_ and correctly determines that my entity is dirty and inserting it. but it ALSO - for reasons I still can not fathom - subsequently UPDATES this, just inserted entity, while also providing null value for `@CreationTimestamp`, thus violating constraint on the table thus failing UPDATE. 

And in 2.9.2, whereas my POJO is being compared via `JsonNode#equals`, for whatever reason, both loaded and current POJO states seem to be an empty JSON node, so they seem to be equal to the dirty-checking mechanism, so there is no UPDATE, but INSERT happens just fine, and all goes well. 

I must be missing something obvious... :(

**Comment by 62mkv** [comment]
(I've posted a big comment but now it seems that the problem was with something else.. I will investigate further)

**Comment by vladmihalcea** [comment]
I don't know what the `@Data` or `@Jacksonized` annotations are. I'm glad you found a workaround.

**Comment by zxmarcos** [comment]
POJOs should also implement Serializable, otherwise, Hibernate will mark the field as dirty if it is not null. Along with `@Data` this is what solved the issue for me.

**Comment by vladmihalcea** [comment]
@zxmarcos All JPA attributes should be `Serializable`. The specification requires that, as indicated by the Hibernate documentation.
