### ISSUE TITLE
Request to use jackson-databind-2.10.0 or later

### ISSUE THREAD

**Issue by dforrest88** [vladmihalcea/hibernate-types#144]
Several security vulnerabilities have been identified with jackson-databind-2.9.10 and earlier. This request is to update the dependency to 2.10.0 or later where the vulnerabilities have been resolved.

**Comment by vladmihalcea** [comment]
The 5.2 module was upgraded to use the `2.9.10.1` Jackson Databind version. The other modules are meant to be compiled and run with the minimum version of Java required by the associated Hibernate version. Now, since Jackson does not maintain those branches, nothing can be done about it. It's the responsibility of the user to upgrade these dependencies, as they are transient to this project.
