### ISSUE TITLE
Spring Boot-friendly way to support both JsonStringType and JsonBinaryType depending on dialect

### ISSUE THREAD

**Issue by dartov** [vladmihalcea/hibernate-types#188]
Hello,

I'm using Spring Boot and I couldn't find an elegant way to support JSON column with multiple target databases, selecting specific type depending on dialect, I have to ditch Hibernate-Types and resort to custom dialects..
I know it's possible to provide XML mapping that will take precedence, but there's no way in JPA AutoConfiguration to supply just XML that will override annotated class, it's either full XML or nothing (they don't allow extending HibernateJpaAutoConfiguration any more).
I think it'll be great to have some examples in documentation for that case.

(Understanding this is more Spring Boot issue than Hibernate-Types, feel free to disregard it, just a suggestion; it also looks like there's a feature addressing this coming in #174, again feel free to disregard it as a duplicate)

**Comment by vladmihalcea** [comment]
The #174 issue aims to provide a single `JsonType` that would delegate the calls to an existing JSON Hibernate Type based on the current Dialect and the entity attribute type.

If your employer wants to sponsor this feature, I could implement it via my [consulting services](https://vladmihalcea.com/consulting/). Or, you could try to implement it and send me a Pull Request with your proposal.

Anyway, I'm going to close this issue since it's, indeed, already covered by #174. The generic `JsonType` will work with any Hibernate application, not just Spring Boot.
