### ISSUE TITLE
Stop trying to force your product hypersistence optimizer on us

### ISSUE THREAD

**Issue by N4zroth** [vladmihalcea/hibernate-types#194]
The Configuration class is spamming my log with some bloat about hypersistence optimizer, a product you sell. If I disable the log it's just printed to System.out and can't be removed which is completely unacceptable for an open source lib imho. I've used a lot of libraries and have never seen anything like it. Could you please remove the spam?

**Comment by vladmihalcea** [comment]
Of course, it can be removed. It takes just 2 minutes to go through the `README` file in order to find out how to disable it.

And, there you will also find the reason why this banner exists, and I will not remove it because that's the only financial benefit I get from spending over 10k worth of consulting time for sponsoring the development of this project.

If you don't like it, you are free to fork it, remove it, and use your own version that doesn't have the banner.
