### ISSUE TITLE
Stop trying to force your paid product hypersistence whatever on us

### ISSUE THREAD

**Issue by N4zroth** [vladmihalcea/hibernate-types#195]
Your library is spamming my log telling me to try your product which is unacceptable for an open source lib. If I disable the log, it gets printed to System.out. Really shady behaviour. Could you please remove this?
Thanks!

**Comment by N4zroth** [comment]
Also, just deleting the issues doesn't raise my trust in this either.

**Comment by vladmihalcea** [comment]
The doc explains [).

> Your library is spamming my log telling me to try your product which is unacceptable for an open source lib.

OSS authors are free to do whatever they want with their fork. If you don't like it, feel free to fork it and remove the banner yourself.

> If I disable the log, it gets printed to System.out. Really shady behaviour.

You're doing it all wrong because you didn't [read the README file](how to remove the Hypersistence Optimizer banner from the log](https://github.com/vladmihalcea/hibernate-types#how-to-remove-the-hypersistence-optimizer-banner-from-the-log).

> Really shady behaviour.

You don't have to use this framework if you don't like it. 

> Could you please remove this?

Actually, [you can remove the banner yourself](https://github.com/vladmihalcea/hibernate-types#how-to-remove-the-hypersistence-optimizer-banner-from-the-log).

> Also, just deleting the issues doesn't raise my trust in this either.

I use GitHub issues for technical problems only. That's why this issue is going to be deleted as well.

You can open it 100 times if you want, but it will be deleted anyway.

Cheers!
