### ISSUE TITLE
Array Types mapping not compatible with HIbernate 5.4.12.Final version

### ISSUE THREAD

**Issue by sriram-rangarajan** [vladmihalcea/hibernate-types#201]
Hello, 

I am using hibernate types for mapping Java arrays to DB array types. After updating hibernate to version to 5.4.12.Final started getting the following errors: 

No Dialect mapping for JDBC type: 2003

I am currently using this approach to map String array.
https://vladmihalcea.com/how-to-map-java-and-sql-arrays-with-jpa-and-hibernate/

Please let me know if more info is needed on my side. 

Thanks!

**Comment by vladmihalcea** [comment]
I upgraded to 5.4.12 and all the tests in the `hibernate-types-52` module run just fine. [This is the commit that proves it](https://github.com/vladmihalcea/hibernate-types/commit/6dae8ac1cbc401974b741b4882ba3c2bf48ee196).

So, if you can create a replicating test case, I will take a look at it. Otherwise, I'll close the issue.

**Comment by sriram-rangarajan** [comment]
ack! I will work on the test cases

**Comment by vladmihalcea** [comment]
Great, thanks

**Comment by sriram-rangarajan** [comment]
I did more debugging on my side.

I am using hibernate envers for entity auditing. The issue is incompatible mapping with hibernate-envers:5.4.12.Final. Is there any workaround for the same? Closing this issue as this package is not depenedent on envers package.

**Comment by vladmihalcea** [comment]
I don't know why Envers might break something. You can open a bug for Hibernate if you have a replicating test case.
