### ISSUE TITLE
How to log values converted by ImmutableType?

### ISSUE THREAD

**Issue by akefirad** [vladmihalcea/hibernate-types#283]
It seems the way `ImmutableType#nullSafeSet`  is implemented breaks the logic of enabling logs to see the value of columns in `BasicBinder`. Currently if one wants to see them she needs to enable trace logs for `org.hibernate.type.descriptor.sql.BasicBinder` (and `org.hibernate.type.descriptor.sql.BasicExtractor` for extracted data). But with `ImmutableType`s it won't work since it doesn't go through `BasicBinder`.
1. Is this by design or just something missing feature?
2. What's the best way to implemented this (as a PR to this library)?
3. If not, is there any workaround to see the values in logs somewhere somehow?

**Comment by vladmihalcea** [comment]
Not all Hibernate Core types use the `Binder`. For instance, `EnumType` is implemented as a `UserType`, just like the `ImmutableType` in this project.

The `ImmutableType` cannot use the `Binder` contract since it lacks the `javaDescriptor` and `sqlDescriptor` contract.

So, one workaround would be to make the `ImmutableType` class use an `org.hibernate.type.descriptor.sql.ImmutableType` logger, but that's a hacky solution.

A much better approach is to use a better logging framework, like `datasource-proxy`, which works even if you combine multiple frameworks. Check out [this article](https://vladmihalcea.com/the-best-way-to-log-jdbc-statements/) for more details.
