### ISSUE TITLE
@JsonProperty and @JsonAlias annotations incompatible with hibernate-types library

### ISSUE THREAD

**Issue by Chexpir** [vladmihalcea/hibernate-types#315]
Steps to reproduce:
- 1. Use in some class (In this case, for deserializing Quarkus rest-client response)@JsonProperty or @JsonAlias. 

```
import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@Getter
@Setter
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class AuthenticationResponseDTO {
    @JsonAlias("access_token")
    String accessToken;
    @JsonAlias("expires_in")
    Integer expiresIn;
    @JsonAlias("token_type")
    String tokenType;
}
```

- 2. Import hibernate-types.

Expected: Unrelated class continues working.
Actual: it starts failing, ignoring the annotations, so you need to change field names to access_token.

Note: hibernate naming strategy does not work as a solution, as it´s unrelated with this.

I have also tried
```@JsonNaming(value = PropertyNamingStrategy.SnakeCaseStrategy.class)``` 
but it does not work.

**Comment by vladmihalcea** [comment]
Hibernate Types is for writing JSON objects to a relational database system and fetching that data back. All that happens in the context of the data access layer. 

The description in your issue is related to how Quarkus serializes JSON objects on the web layer, which is totally unrelated to Hibernate Types.

In your case, it could be a Jackson version incompatibility, but I doubt there's anything to change in this framework as Hibernate Types does not provide a hard dependency for Jackson.

So, if you think there's an issue, then you should debug it, provide a replicating test case, and come up with a Pull Request that fixes the issues. I'll check it out when you submit a Pull Request.

**Comment by Chexpir** [comment]
Sorry for bothering you. I thought I tested empirically issue was on this library, but it appears to be in quarkus-resteasy-jsonb
Thanks!

**Comment by vladmihalcea** [comment]
@Chexpir I'm glad I could help. You should probably discuss it further with the Quarkus team and see how they can fix the problem.
