### ISSUE TITLE
PostgreSQLTSVectorType persisted not as expected

### ISSUE THREAD

**Issue by paruir** [vladmihalcea/hibernate-types#325]
According to postgres [documentation](https://www.postgresql.org/docs/11/textsearch-controls.html) 
`select to_tsvector('english', 'a fat  cat sat on a mat - it ate a fat rats');
` 
should return
`
 'ate':9 'cat':3 'fat':2,11 'mat':7 'rat':12 'sat':4
`
As far as I understand during persist data with type PostgreSQLTSVectorType have to be equal to the result of to_tsvector() call.
But in my case string "test string for db" saved to DB as the **"'test' 'string' 'for' 'db'"** not like "'test':1 'string':2 'for':3 'db':4"

And that causes that next sql query doesn't return any result
`select * from table where tsvector @@ to_tsquery('for')`

only this query works for mentioned tsvector

`select * from table where tsvector @@ to_tsquery('test')`

But all search queries are work with the next value of tsvector column: "'test':1 'string':2 'for':3 'db':4"

**Comment by vladmihalcea** [comment]
The `PostgreSQLTSVectorType` saves the associated `String` to the `tsvector` column as-is. The Hibernate Type just binds the associated entity attributes to the underlying column value via the `PreparedStatement`.

Luckily, the project is open-source, so you can try to see how you can accommodate the `to_tsvector` function call. Looking forward to reviewing your Pull Request with the fix proposal.

**Comment by paruir** [comment]
I see, thank you very much for explanation. Looks like this can be done by dialect extension or by function implementation on application level. Let's see how I can do this

**Comment by vladmihalcea** [comment]
First, you could provide a test case in this repository where you demonstrate how it should work in JDBC. Afterward, I'll take a look at it and see what Hibernate feature could be used to integrate it.

**Comment by jwgmeligmeyling** [comment]
I'm not sure whether you will achieve the desired result by using `to_tsquery`.

For Hibernate types, I think you want that converting the column value back and forth the Java type yields the same result. Otherwise you'll overwrite the tsvector with a corrupted state with each flush, as it will try call `to_tsvector` on its own output. Thus you'll endup with the result of `to_tsvector(to_tsvector("the string")::varchar)`.  For any type it should be so that column value -> java value -> column value.

The `TsvectorType` is not intended for conversion of strings to tsvectors, its a type to map tsvectors as-is.

If you want to call `to_tsvector` on your input string, its probably better to use a `@ColumnTransformer` for that purpose.

**Comment by vladmihalcea** [comment]
Thanks, @jwgmeligmeyling for providing more context. I'm going to close this issue as there's nothing to change at the moment.
