### ISSUE TITLE
Support JSON in MySQL

### ISSUE THREAD

**Issue by mas15** [vladmihalcea/hibernate-types#397]
As I see the hibernate-types converts json data into a String column when using MySQL. Are you planning to support a JSON type column?

**Comment by vladmihalcea** [comment]
Nope. That's how the JSON is passed to the DB so that the String is saved in a JSON column. That's how the MySQL JDBC Driver wants that JSON column value to be passed, and that's how the library passes it.

If you run [this MySQL test case](https://github.com/vladmihalcea/hibernate-types/blob/master/hibernate-types-55/src/test/java/com/vladmihalcea/hibernate/type/json/MySQLJsonTypeSetTest.java#L113), you will see how it works.
