### ISSUE TITLE
Add support for Hibernate 6

### ISSUE THREAD

**Issue by 120011676** [vladmihalcea/hibernate-types#401]
Is Hibernate 6 supported?

**Comment by vladmihalcea** [comment]
Hibernate 6 is in development. Once it reached the 6.0 version, a new module will be added to add support for Hibernate 6. 

If you are in a hurry, you can provide a Pull Request for it. You don't have to wait for me to add it. That's the beauty of open-source.

**Comment by jwgmeligmeyling** [comment]
6.0 was released yesterday. I hope to give it a spin any time soon for [https://github.com/jwgmeligmeyling/hibernate-types-querydsl-apt](jwgmeligmeyling/hibernate-types-querydsl-apt) anyway. I still have to look into the user type system. I believe the type system changed quite heavily, but the release notes seem to suggest otherwise, so I guess it remains to be seen. I'll contribute any of my works back if anyone doesn't get to it before me 😄

**Comment by vladmihalcea** [comment]
Thanks for the heads up

**Comment by jwgmeligmeyling** [comment]
Awesome! 👍🏻

**Comment by vladmihalcea** [comment]
@jwgmeligmeyling I managed to find a way to retain the old behavior that makes it so much easier to provide a single type rather than setting the `JavaType` and `JdbcType` separately. All in all, it looks good for the first release.
