### ISSUE TITLE
how to display an array of Range <LocalDate> in a jsp page

### ISSUE THREAD

**Issue by HarleyQuin873** [vladmihalcea/hibernate-types#440]
I can't understand why my for is not working in the jsp page, Can anyone help me? I don't feel like changing the design. When I finish the project and I have delivered it to the professor, I will publish it on linkedin to facilitate job interviews. Thank you.

https://discourse.hibernate.org/t/how-to-display-array-range-localdate-in-a-jsp-page/6355

**Comment by vladmihalcea** [comment]
This is the second time you are opening an issue here for a problem that's unrelated to the project itself. 

The goal of the project is to persist JSON data and fetch it using Hibernate, and the tests prove that it works just fine. What's not working for you is related to how you built your web application. 

The situation you are currently in is just a typical day in a programmer's life. Once you get the job, this is how every day is going to be. So, your goal is to figure out how to solve any possible issue you'll face because there are millions of them awaiting you to fix.
