### ISSUE TITLE
HibernateTypesContributor is not register any types for Postgres

### ISSUE THREAD

**Issue by SergeiKhmelevSPA** [vladmihalcea/hibernate-types#441]
Hibernate ORM core version: 5.6.8.Final
Hibernate Types 55 version: 2.16.2

During Spring Boot context creation `MetadataBuildingProcess` handles types provided via `TypeContributor`. So `com.vladmihalcea.hibernate.type.HibernateTypesContributor` also tries to contribute types. The problem is that it couldn't do it for Postgres because of the condition 
```java
// org.hibernate.dialect.PostgreSQLDialect
if(dialect instanceof PostgreSQLDialect)
```

`PostgreSQLDialect` is deprecated and `PostgreSQL82Dialect` should be used instead.

**Comment by vladmihalcea** [comment]
Thanks for the tip. The `PostgreSQLDialect` is the default one in Hibernate 6, and I forgot to change it for 55.

**Comment by SergeiKhmelevSPA** [comment]
By the way, I noticed the same issue with `OracleDialect`

**Comment by vladmihalcea** [comment]
Don't worry, I'll amend the commit for Oracle and/or SQL Server too

**Comment by stevefranchak** [comment]
When might it be expected for 2.16.3 to be released? I'm unable to use hibernate-types until it is due to this issue.

**Comment by vladmihalcea** [comment]
On a spare time basis, probably autumn. It depends on my other projects.

If your company needs it sooner, I could do a release sooner if they agree to pay the time it takes me to run all tests and do the release.

**Comment by victornoel** [comment]
Hello @vladmihalcea, I am hitting a small issue with this fix: in my codebase, I am using version 2.16.2 and I never really realized that `HibernateTypesContributor` wasn't properly registering types for PostgreSQL (it seems it never was a problem when using json types).

I have legacy code that is using `String[]` as a type for a columns and is currently persisted as `bytea` in the db (this is the default behavior of hibernate 5.6 apparently).

I upgraded to 2.16.3 (because of the serialization issue from #438) and now, `StringArrayType` being properly registered, hibernate tries to persist my `String[]` column as a `text[]`.

How would I go about disabling this only for that column?

Thank you, I hope it's ok to ask this here :)

**Comment by vladmihalcea** [comment]
First, Hibernate Types 2 is an ancient version. Thr project is called Hypersistence Utils and the latest version is 3.5.3.

Second, I no longer have the time to offer free support for this library. I only offer support via consulting.

**Comment by victornoel** [comment]
@vladmihalcea ok, thank you in any case for this great library :)

**Comment by vladmihalcea** [comment]
You're welcome.

**Comment by victornoel** [comment]
For anybody coming through here looking for the answer to my question, the solution was to force the type of the column to `SerializableType` as it seems to be the fallback Hibernate uses to persist `String[]`:
```java
@Basic
@Type(type = "serializable")
private String[] column;
```
