### ISSUE TITLE
org.hibernate.resource.beans.container.internal.NotYetReadyException: CDI BeanManager not (yet) ready to use

### ISSUE THREAD

**Issue by anjunar** [vladmihalcea/hibernate-types#481]
When using hibernate-types-60 with the new Wildfly Server 27 this error Message occors.

**Comment by vladmihalcea** [comment]
I haven't used Wildfly or JBoss since 2008, so I won't be able to help you with this.

The library is fairly simple to use as illustrated by the tons of integration tests in this repository. Most likely, the problem you're having is caused by the JBoss Modules, but that doesn't;t have to do anything with this library. You would probably bump into this issue with any other external library.

Well, that's the downside of application servers and the reason why Red Hat moved on to Quarkus, which is closer to Spring.
