### ISSUE TITLE
Java Enum to PostgreSQL Enum (method override problem)

### ISSUE THREAD

**Issue by JoeCDNA** [vladmihalcea/hibernate-types#5]
`nullSafeSet()` in `com.vladmihalcea.hibernate.type.basic.PostgreSQLEnumType` is never triggered.
It seems that the currently implemented `PostgreSQLEnumType` doesn't have the proper method definition to override its parent (`org.hibernate.type.EnumType`).

Current:
```
public void nullSafeSet(PreparedStatement st, Object value, int index, SharedSessionContractImplementorsession) throws HibernateException, SQLException
```
Should be:
```
public void nullSafeSet(PreparedStatement st, Object value, int index, SessionImplementor session) throws HibernateException, SQLException
```

Note that the class `SharedSessionContractImplementor` cannot be found in my implementation.

**Comment by vladmihalcea** [comment]
The [5.2 PostgreSQLEnumType](https://github.com/vladmihalcea/hibernate-types/blob/master/hibernate-types-52/src/main/java/com/vladmihalcea/hibernate/type/basic/PostgreSQLEnumType.java) is different than [5.1 PostgreSQLEnumType](https://github.com/vladmihalcea/hibernate-types/blob/master/hibernate-types-5/src/main/java/com/vladmihalcea/hibernate/type/basic/PostgreSQLEnumType.java) because the `UserType` signature has changed in 5.2.

What you did was to use the hibernate-type-5.2 against HIbernate ORM 5.1 or older.
