### ISSUE TITLE
JsonStringType throws an NPE when using with Hibernate XML

### ISSUE THREAD

**Issue by andyflury** [vladmihalcea/hibernate-types#70]
Hi @vladmihalcea 

Congrats to your project! 

I'm try to use your JsonStringType with Hibernate XML (unfortunately we are not using Hibernate Annotations in our project). The field is configured like this.

```
<property name="properties">
    <column name="PROPERTIES" not-null="true" unique="false" sql-type="json"/>
    <type name="com.vladmihalcea.hibernate.type.json.JsonStringType"/>
</property>  
```
Unfortunately com.vladmihalcea.hibernate.type.json.internal.JsonTypeDescriptor.setParameterValues (line 57) is receiving an empty Properties object and throws an NPE due to that.

The fix seems to be trivial:

```
@Override
public void setParameterValues(Properties parameters) {
    final XProperty xProperty = (XProperty) parameters.get(DynamicParameterizedType.XPROPERTY);
    if (xProperty instanceof JavaXMember) {
        type = ReflectionUtils.invokeGetter(xProperty, "javaType");
    } else if (parameters.containsKey(PARAMETER_TYPE)) {
        type = ((ParameterType) parameters.get(PARAMETER_TYPE)).getReturnedClass();
    }
}
```

At first I thought we'd need to define some extra parameters in the Hibernate XML, but that does not seem to be necessary.

Does this make sense?

**Comment by vladmihalcea** [comment]
@andyflury The XML `type` could also contain a short-name for the `type` as defined by the `type-def` tag, in which case this solution will break.

The legacy XML mappings are deprecated anyway, and since you can combine XML and annotations so that you can define just the `@Type` definitions using annotations, I think this issue does not need any change.

You can use `@TypeDef` at package-level or at some base entity level so that's further inherited. This way, you don't have to declare it in XML.

**Comment by vladmihalcea** [comment]
You can use XML and annotations, you don't have to choose one or the other. [This article](https://vladmihalcea.com/how-to-replace-the-table-identifier-generator-with-either-sequence-or-identity-in-a-portable-way/) explains how you can do that.

The current issue here is with Hibernate since it does not apply the dynamic parameters to HBM mappings. So, you need to open a Jira issue with a replicating test case for it.

I don't think it's worth adding this change since it will add an additional complexity to the framework for a temporary problem that's related to Hibernate.

**Comment by vladmihalcea** [comment]
I think that the dynamic parameters cannot work for XML. Send me a Pull Request with a replicating test case and a fix and I'll review it when it's ready.

**Comment by andyflury** [comment]
Thanks @vladmihalcea 
Yes, I'm aware that technically annotations and XML can be mixed. In our case this was more of a management decision to stick to XML for now, so even if it is technically possible I have to stick to XML.

Is there some other way with your library to set the actual type in use by JsonStringType? I see that the class has two constructions that take a javaType argument. Is there a way to use these constructors?

**Comment by andyflury** [comment]
Ok, I'll prepare a PR with a test case and a fix. Thanks!

**Comment by vladmihalcea** [comment]
You can register the `JsonStringType` like this:

```
configuration.registerTypeContributor( (typeContributions, serviceRegistry) -> {
	typeContributions.contributeType( JsonStringType.INSTANCE );
} );
```

or via the `MetadataBuilder` during bootstrap:

```
ServiceRegistry standardRegistry =
    new StandardServiceRegistryBuilder().build();

MetadataSources sources = new MetadataSources( standardRegistry );

MetadataBuilder metadataBuilder = sources.getMetadataBuilder();

metadataBuilder.applyBasicType( JsonStringType.INSTANCE );
```

**Comment by vladmihalcea** [comment]
I also think that this will work, but I didn't test it:

```
<type name="com.vladmihalcea.hibernate.type.json.JsonStringType">            
    	<param name="org.hibernate.type.ParameterType">MyCustomJsonObject</param>
</type>

```
I noticed that you used `java.util.HashMap` to store the JSON, but that's not supported. You need a Java Bean that can be properly marshalled to a JSON.

**Comment by vladmihalcea** [comment]
> The last two constructors currently have a Class parameter, however those would need to be Type parameters

I think you could achieve the same goal to set the `javaType` via the `setParameterValues` as long as you provide the `Properties` object so that you get the Type from the `PARAMETER_TYPE` property:

    type = ((ParameterType) parameters.get(PARAMETER_TYPE)).getReturnedClass();

So, I don't think we need to modify the constructor either. All in all, I'm glad it works for you.

**Comment by andyflury** [comment]
> I think you could achieve the same goal to set the javaType via the setParameterValues as long as you provide the Properties object so that you get the Type from the PARAMETER_TYPE property:
> 
> type = ((ParameterType) parameters.get(PARAMETER_TYPE)).getReturnedClass();

Problem is again that `getReturnedClass()` returns a `Class` and not a `Type`. `ParameterizedType `is a `Type `but not a `Class`.

When running your `MySQLGenericJsonTypeTest` actually the following line is executed instead of the one you mentioned:

`type = ReflectionUtils.invokeGetter(xProperty, "javaType");`

Coming back to my suggestion. The `JsonStringType` constructor args `Class` are really only used when calling the constructor of `JsonTypeDescriptor` which expects a `Type` argument. I therefore don't think the `JsonStringType` constructor arg needs to be more restrictive (`Class`) then the `JsonTypeDescriptor` arg (`Type`). Don't you agree?

**Comment by vladmihalcea** [comment]
Send me a Pull Request with a test case containing the HBM mapping, the bootstrap example and the constructor signature change. I'll review it when it's ready. Cheers.

**Comment by andyflury** [comment]
I just created a pull request with the constructor signature change. I think there is no need to cover the HBM mapping after our discussion. Creating the JsonStringType programatically works just fine for our case.

**Comment by vladmihalcea** [comment]
I won't integrate it unless you provide a test case too. Cheers.

**Comment by vladmihalcea** [comment]
They should probably have different names. Anyway, this only applies if the Type is provided during bootstrap, not via annotations.
