### ISSUE TITLE
java.lang.NoClassDefFoundError: org/hibernate/annotations/common/reflection/XProperty

### ISSUE THREAD

**Issue by mnesarco** [vladmihalcea/hibernate-types#93]
Hi, I am trying to use this lib in a webapp, deployed to Wildfly 16 (hibernate 5.3.9).
I have added the dependency:

```
    <dependency>
      <groupId>com.vladmihalcea</groupId>
      <artifactId>hibernate-types-52</artifactId>
      <version>2.4.3</version>
    </dependency>

```

My dependency to hibernate-code is in provided scope.

I got this exception on deploy:

```
WFLYCTL0186:   Services which failed to start:      service jboss.persistenceunit."aurora.war#pu": java.lang.NoClassDefFoundError: org/hibernate/annotations/common/reflection/XProperty
WFLYCTL0448: 48 additional services are down due to their dependencies being missing or failed

```

Do I have to add an explicit dependency to hibernate-annotations in the compile scope?

**Comment by vladmihalcea** [comment]
This is most likely caused by a [`hibernate-commons-annotations`](https://mvnrepository.com/artifact/org.hibernate.common/hibernate-commons-annotations) incompatibility. Check out the application server for the version supplied for this dependency and compare it to the one used by this GitHub repository.

**Comment by kiview** [comment]
This seems to happen when using `hibernate-commons-annotations-5.0.1`, which is the dependency of Hibernate `5.1.10`.

So this means `hibernate-types` is incompatible with Hibernate `5.1.10`, or is there are workaround?

**Comment by vladmihalcea** [comment]
Currently, the only workaround is to upgrade the `hibernate-commons-annotations` version. That should not impact Hibernate, so why not do the update anyway?

**Comment by cec** [comment]
Hi @vladmihalcea and @kiview  

I'm on WildFly 10, which comes with `hibernate-commons-annotations-5.0.1.Final`.

I added `hibernate-commons-annotations-5.1.0.Final` and updated `module.xml` to point to it.

In `pom.xml` I added
````
        <dependency>
            <groupId>org.hibernate.common</groupId>
            <artifactId>hibernate-commons-annotations</artifactId>
            <version>5.1.0.Final</version>
            <scope>provided</scope>
        </dependency>
````

However I still get `java.lang.ClassNotFoundException: org.hibernate.annotations.common.reflection.XProperty `.

Did you manage to fix this?

Otherwise I'll prepare a reproduction project so that it can be analyzed and resolved

**Comment by vladmihalcea** [comment]
I haven't used Wildfly, so I have no idea what might cause the problem. Most likely this is a Wildfly issue. Anyway, if you replicate it, you need to debug it and see whether there's something to be fixed.

**Comment by imbananko** [comment]
same problem for me with WildFly

**Comment by vladmihalcea** [comment]
@imbananko If you find a solution, don't forget to add it here to help others in the future to overcome this issue.

**Comment by nubenum** [comment]
So in my case the solution was to create the `jboss-deployment-structure.xml` file in the `webapp/WEB-INF` directory with the following content:

```
<?xml version="1.0" encoding="UTF-8"?>
<jboss-deployment-structure xmlns="urn:jboss:deployment-structure:1.2">
    <deployment>
        <dependencies>
            <module name="org.hibernate.commons-annotations"/>
        </dependencies>
    </deployment>
</jboss-deployment-structure>
```

**Comment by vladmihalcea** [comment]
@nubenum Thanks for sharing your solution. I haven't used JBoss since 2008 and have no idea what was needed for using this lib.
